spring:
  profiles.active: default

---

server:
  port: 9999
  session.timeout: 30

---

logging:
  level:
    root: INFO
    org.springframework.boot: WARN
#    org.springframework.boot.autoconfigure: WARN
#    org.springframework.context: WARN
    org.springframework.web: WARN
#    org.springframework.security: WARN

#  file: logs/max.log

---
